### ISSUE TITLE
读取scaling_available_frequencies节点有可能会read failed: ENODEV (No such device)

### ISSUE THREAD

**Issue by zienn** [Knight-ZXW/moonlight-apm-android#2]
```
java.io.IOException: read failed: ENODEV (No such device)
    at libcore.io.IoBridge.read(IoBridge.java:523)
    at java.io.FileInputStream.read(FileInputStream.java:313)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.BufferedReader.fill(BufferedReader.java:172)
    at java.io.BufferedReader.readLine(BufferedReader.java:335)
    at java.io.BufferedReader.readLine(BufferedReader.java:400)
    at kotlin.io.LinesSequence$iterator$1.hasNext(ReadWrite.kt:79)
    at kotlin.sequences.SequencesKt___SequencesKt.forEach
    at kotlin.io.TextStreamsKt.forEachLine(ReadWrite.kt:33)
    at kotlin.io.FilesKt__FileReadWriteKt.forEachLine
    at kotlin.io.FilesKt__FileReadWriteKt.readLines(FileReadWrite.kt:219)
    at kotlin.io.FilesKt__FileReadWriteKt.readLines$default
```

**Comment by Knight-ZXW** [comment]
确实会有这种情况，需要做好容错处理
